name = "MDSplus"
uuid = "4f15b78f-3269-40a2-9077-c888721e3b2a"
authors = ["Luke Stagner <stagnerl@fusion.gat.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
Libdl = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
